# Generated by Django 4.2.2 on 2023-07-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_menuitems_singlemenuitem_delete_menu_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SingleMenuItem",
        ),
    ]
