# Generated by Django 4.2.3 on 2023-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_singlemenuitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("inventory", models.IntegerField()),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menu Items",
            },
        ),
        migrations.DeleteModel(
            name="MenuItems",
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Booking Records",
            },
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="BookingDate",
            new_name="booking_date",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="No_of_guests",
            new_name="number_of_guests",
        ),
    ]
