# Generated by Django 4.2.2 on 2023-07-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_menu_delete_menuitems_alter_booking_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={},
        ),
        migrations.RemoveField(
            model_name="booking",
            name="booking_date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="number_of_guests",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="menu",
            name="title",
        ),
        migrations.AddField(
            model_name="booking",
            name="first_name",
            field=models.CharField(default="Your name", max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="booking",
            name="reservation_slot",
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="menu",
            name="menu_item_description",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="menu",
            name="name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="menu",
            name="price",
            field=models.IntegerField(),
        ),
    ]
